[project]
name = 'grantecho'
description = 'SIP-031 Grant Proposal Tracker for Stacks Governance'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.proposal-tracker]
path = 'contracts/proposal-tracker.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
